before_script:
    - docker-compose down --rmi all --remove-orphans
    - echo y | docker network prune

build_staging:
  variables:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DB_LLTK_PW: $DB_LLTK_PW
      SECRET_KEY: $SECRET_KEY
      ENV: production
  stage: deploy
  tags : 
    - indico-dev
  only:
    refs:
      - master
  script:
    # - export PYTHONDONTWRITEBYTECODE=1
    -  docker-compose up -d --force-recreate
