build_prod:
  before_script:
    - docker-compose -f docker-compose.prod.yml down --rmi all
    - echo y | docker network prune
  variables:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SECRET_KEY: $SECRET_KEY
      ENV: production
  stage: deploy
  tags : 
    - indico-dev
  only:
    refs:
      - master
  script:
    # - export PYTHONDONTWRITEBYTECODE=1
 #   - chmod +x ./api/docker-entrypoint.sh
    -  docker-compose -f docker-compose.prod.yml up -d --force-recreate


build_staging:
  before_script:
    - docker-compose -f docker-compose.dev.yml down --rmi all
    - echo y | docker network prune
  variables:
      POSTGRES_USER: $POSTGRES_USER_DEV
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD_DEV
      SECRET_KEY: $SECRET_KEY_DEV
      ENV: production
  stage: deploy
  tags : 
    - indico-v2
  only:
    refs:
      - dev
  script:
    # - export PYTHONDONTWRITEBYTECODE=1
    # - chmod +x ./api/docker-entrypoint.sh
    -  docker-compose -f docker-compose.dev.yml up -d --force-recreate

