before_script:
    - docker compose down --rmi all --remove-orphans
    - echo y | docker network prune

build_staging:
  stage: deploy
  tags : 
    - indico-dev
  only:
    refs:
      - master
  script:
    # - export PYTHONDONTWRITEBYTECODE=1
    -  docker compose up -d --force-recreate
