version: '3.9'
 
services:
  database:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - indico_prod

  indico:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    ports:
      - "5000:5000"
    environment:
      - DATABASE=postgres
      - ENV
      - DB_HOST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - SECRET_KEY
      - SQL_DB_PORT=5432
      - ADMIN_USERNAME
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
    volumes:
      - "./api/app:/opt/app"
    restart: always
    networks:
      - indico_prod

  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_FILTER=name=indico
    ports:
      - 5453:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - indico_prod

  web:
    build: ./app/
    ports:
      - 80:8080
    restart: always
    networks:
      - indico_prod

volumes:
  postgres_data:

networks:
  indico_prod: