version: '3.9'
 
services:
  sgbd:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    volumes:
       - ./pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
    depends_on:
      - "database"

  database:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    # healthcheck:
    #   test: ["CMD", "test" ,"-f", "/var/lib/postgresql/data/ready.flag"]
    #   interval: 1s
    #   timeout: 1s
    #   retries: 30
    #   start_period: 1s
    
  indico:
    build: ./api
    links:
      - database
    # depends_on:
    #   database:
    #     condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DATABASE=postgres
      - ENV
      - DB_HOST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - SECRET_KEY
      - SQL_DB_PORT=5432
    volumes:
      - "./api/app:/opt/app"
    restart: always

  # nginx:
  #   image: nginx:latest
  #   links:
  #     - indico
  #   volumes:
  #     - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  #   ports:
  #     - "8080:8080"
  #   restart: always

  web:
    build: ./app/
    ports:
      - 80:8080
    restart: always

volumes:
  postgres_data:
