version: '3.9'
 
services:
  databasedev:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5431:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: always
    networks:
      - indico_dev

  indico-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - databasedev
    links:
      - databasedev
    ports:
      - "5001:5000"
    environment:
      - DATABASE=postgres
      - ENV
      - DB_HOST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@databasedev:5432/${POSTGRES_DB}
      - SECRET_KEY
      - SQL_DB_PORT=5432
    volumes:
      - indico_dev_data:/opt/app/data
    restart: always
    networks:
      - indico_dev

  dozzle-dev:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_FILTER=name=indico
    ports:
      - 5454:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - indico_dev

volumes:
  postgres_data_dev:
  indico_dev_data:

networks:
  indico_dev: